# Generated by Django 5.2 on 2025-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='question',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
